Coordinate access to outgoing websocket communication.
It turns out that Java 11 HttpClient or rather WebSocket layer of it is not thread safe.
This leads to situations where paralell replies can be pushed to it. Client then fails with a:

java.util.concurrent.CompletionException: java.lang.IllegalStateException: Send pending
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) [?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) [?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) [?:?]

A workaround is making sure that there is always only one thread which publish websocket frames.

Signed-off-by: Łukasz Dywicki <luke@code-house.org>